package com.kubeshift.remediate.service;

import com.kubeshift.remediate.model.PatchType;
import com.kubeshift.remediate.model.RemediationRequest;
import com.kubeshift.remediate.model.ResourcePatch;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.util.HashMap;
import java.util.Map;

@Service
@Slf4j
@RequiredArgsConstructor
public class PatchGeneratorService {

    @Value("${kubeshift.remediation.min-cpu-request:50m}")
    private String minCpuRequest;

    @Value("${kubeshift.remediation.min-memory-request:64Mi}")
    private String minMemoryRequest;

    public String generatePatch(RemediationRequest request, PatchType type) {
        log.info("Generating {} patch for container {} in {}", type, request.containerName(), request.deploymentName());
        
        return switch (type) {
            case KUBERNETES_MANIFEST -> generateK8sPatch(request);
            case HELM_VALUES -> generateHelmPatch(request);
            case KUSTOMIZE_OVERLAY -> generateKustomizePatch(request);
        };
    }

    private String generateK8sPatch(RemediationRequest request) {
        Map<String, Object> container = new HashMap<>();
        container.put("name", request.containerName());
        
        Map<String, Object> resources = buildResourcesMap(request.patches());
        if (!resources.isEmpty()) {
            container.put("resources", resources);
        }

        Map<String, Object> spec = new HashMap<>();
        spec.put("containers", new Object[]{container});

        Map<String, Object> template = new HashMap<>();
        template.put("spec", spec);

        Map<String, Object> outerSpec = new HashMap<>();
        outerSpec.put("template", template);

        Map<String, Object> metadata = new HashMap<>();
        metadata.put("name", request.deploymentName());
        if (request.namespace() != null) {
            metadata.put("namespace", request.namespace());
        }

        Map<String, Object> patch = new HashMap<>();
        patch.put("apiVersion", "apps/v1");
        patch.put("kind", "Deployment");
        patch.put("metadata", metadata);
        patch.put("spec", outerSpec);

        return "# Patch generated by KubeShift\n" + toYaml(patch);
    }

    private String generateHelmPatch(RemediationRequest request) {
        Map<String, Object> resources = buildResourcesMap(request.patches());
        
        Map<String, Object> patch = new HashMap<>();
        patch.put("resources", resources);
        
        return "# Helm values patch generated by KubeShift for " + request.deploymentName() + "\n" + toYaml(patch);
    }

    private String generateKustomizePatch(RemediationRequest request) {
        // Similar to K8s manifest for a simple strategic merge patch
        return "# Kustomize patch generated by KubeShift\n" + generateK8sPatch(request);
    }

    private Map<String, Object> buildResourcesMap(Map<String, ResourcePatch> patches) {
        Map<String, Object> resources = new HashMap<>();
        Map<String, String> requests = new HashMap<>();
        Map<String, String> limits = new HashMap<>();

        for (Map.Entry<String, ResourcePatch> entry : patches.entrySet()) {
            String key = entry.getKey();
            ResourcePatch patch = entry.getValue();
            String val = enforceMinimums(key, patch.recommendedValue());
            
            if (key.startsWith("requests.")) {
                requests.put(key.substring(9), val);
            } else if (key.startsWith("limits.")) {
                limits.put(key.substring(7), val);
            }
        }

        if (!requests.isEmpty()) resources.put("requests", requests);
        if (!limits.isEmpty()) resources.put("limits", limits);
        
        return resources;
    }

    private String enforceMinimums(String resourceKey, String value) {
        // Simple safety checks, a real implementation would parse quantities properly
        if (resourceKey.equals("requests.cpu") && parseCpu(value) < parseCpu(minCpuRequest)) {
            log.warn("Requested CPU {} is below minimum {}, using minimum", value, minCpuRequest);
            return minCpuRequest;
        }
        if (resourceKey.equals("requests.memory") && parseMemory(value) < parseMemory(minMemoryRequest)) {
            log.warn("Requested Memory {} is below minimum {}, using minimum", value, minMemoryRequest);
            return minMemoryRequest;
        }
        return value;
    }
    
    private double parseCpu(String cpu) {
        if (cpu.endsWith("m")) {
            return Double.parseDouble(cpu.replace("m", "")) / 1000.0;
        }
        return Double.parseDouble(cpu);
    }
    
    private double parseMemory(String mem) {
        if (mem.endsWith("Mi")) {
            return Double.parseDouble(mem.replace("Mi", ""));
        }
        if (mem.endsWith("Gi")) {
            return Double.parseDouble(mem.replace("Gi", "")) * 1024.0;
        }
        return Double.parseDouble(mem); // bytes or unknown
    }

    private String toYaml(Object data) {
        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        Yaml yaml = new Yaml(options);
        return yaml.dump(data);
    }
}
