core:
  replicaCount: 1
  image:
    repository: ghcr.io/your-org/kubeshift-core
    pullPolicy: IfNotPresent
    tag: 6426b7ce109b7ed66dba5d00c6a8c4eb67d9dd7f
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

remediate:
  replicaCount: 1
  image:
    repository: ghcr.io/your-org/kubeshift-remediate
    pullPolicy: IfNotPresent
    tag: 6426b7ce109b7ed66dba5d00c6a8c4eb67d9dd7f
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

analyzer:
  replicaCount: 1
  image:
    repository: ghcr.io/your-org/kubeshift-analyzer
    pullPolicy: IfNotPresent
    tag: 6426b7ce109b7ed66dba5d00c6a8c4eb67d9dd7f
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: kubeshift.local
      paths:
        - path: /
          pathType: ImplementationSpecific

github:
  token: ""
