apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeshift.fullname" . }}-core
  labels:
    {{- include "kubeshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubeshift.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
